zwave.aeotec_dsc06106_smart_energy_switch_2:
  ignored: false
  polling_intensity: 1
zwave.aeotec_dsc06106_smart_energy_switch:
  ignored: false
  polling_intensity: 1
sensor.aeotec_dsc06106_smart_energy_switch_energy:
  ignored: false
  polling_intensity: 1
sensor.aeotec_dsc06106_smart_energy_switch_energy_2:
  ignored: false
  polling_intensity: 1
sensor.aeotec_dsc06106_smart_energy_switch_exporting:
  ignored: false
  polling_intensity: 1
sensor.aeotec_dsc06106_smart_energy_switch_exporting_2:
  ignored: false
  polling_intensity: 1
sensor.aeotec_dsc06106_smart_energy_switch_interval_3:
  ignored: false
  polling_intensity: 1
sensor.aeotec_dsc06106_smart_energy_switch_interval_2:
  ignored: false
  polling_intensity: 1
sensor.aeotec_dsc06106_smart_energy_switch_interval:
  ignored: false
  polling_intensity: 1
sensor.aeotec_dsc06106_smart_energy_switch_interval_4:
  ignored: false
  polling_intensity: 1
sensor.aeotec_dsc06106_smart_energy_switch_power_4:
  ignored: false
  polling_intensity: 1
sensor.aeotec_dsc06106_smart_energy_switch_power:
  ignored: false
  polling_intensity: 1
sensor.aeotec_dsc06106_smart_energy_switch_power_3:
  ignored: false
  polling_intensity: 1
sensor.aeotec_dsc06106_smart_energy_switch_power_2:
  ignored: false
  polling_intensity: 1
sensor.aeotec_dsc06106_smart_energy_switch_previous_reading:
  ignored: false
  polling_intensity: 1
sensor.aeotec_dsc06106_smart_energy_switch_previous_reading_3:
  ignored: false
  polling_intensity: 1
sensor.aeotec_dsc06106_smart_energy_switch_previous_reading_2:
  ignored: false
  polling_intensity: 1
sensor.aeotec_dsc06106_smart_energy_switch_previous_reading_4:
  ignored: false
  polling_intensity: 1
